spring:
  datasource:  # mysql ???
    url: jdbc:mysql://localhost:3306/your_database_name?serverTimezone=Asia/Seoul&characterEncoding=UTF-8	# ?????? URL
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC ???? ??? (MySQL? ??)
    username: your_username  # ?????? ??? ??
    password: your_password  # ?????? ????
  application:
    name: webcrud
  mustache:
    cache: false
    suffix: .html

server:
  port: 8080
# spring.application.name=webcrud

